In [42]:
import os
import getpass

import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
import sacrebleu
from tqdm import tqdm

print("Imports OK")
print("torch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

Imports OK
torch version: 2.6.0+cu118
CUDA available: True

In [44]:
from huggingface_hub import login

token = os.environ.get("HF_TOKEN")

if not token:
    print("HF_TOKEN not found in environment.")
    token = getpass.getpass("Enter your Hugging Face access token (input hidden): ").strip()

assert token, "No token provided. Get one at https://huggingface.co/settings/tokens"

login(token=token)
print("Logged in to Hugging Face.")

HF_TOKEN not found in environment.

Enter your Hugging Face access token (input hidden):  ········

Logged in to Hugging Face.

In [ ]:
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

In [46]:
INPUT_CSV = r"C:\Ayushi_Code\english-hindi\Dataset.csv" 
OUTPUT_CSV = "translation_scores.csv"

SOURCE_COL = "English Sentences"       # column with English sentences
REFERENCE_COL = "Hindi Sentences"  # column with gold/reference Hindi translation -> CHANGE to match your CSV

MODEL_ID = "meta-llama/Llama-3.2-1B-Instruct"   # or "meta-llama/Llama-3.2-3B-Instruct"

NUM_SENTENCES = 100
MIN_LEN, MAX_LEN = 5, 50     # sentence length filter, in WORDS
RANDOM_SEED = 42
MAX_NEW_TOKENS = 80

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", DEVICE)

Using device: cuda

In [48]:
df = pd.read_csv(INPUT_CSV,encoding='utf-8-sig')
print("Loaded CSV with shape:", df.shape)
df.head()

Loaded CSV with shape: (10000, 5)

,English Sentences,Hindi Sentences,Word Count (English),Word Count (Hindi),Difference between Word Count (English) and Word Count (Hindi)
0,"However, Paes, who was partnering Australia's ...",आस्ट्रेलिया के पाल हेनली के साथ जोड़ी बनाने वाल...,23.0,28.0,5
1,"Whosoever desires the reward of the world, wit...",और जो शख्स (अपने आमाल का) बदला दुनिया ही में च...,26.0,35.0,9
2,"""The value of insects in the biosphere is enor...","जैव-मंडल में कीड़ों का मूल्य बहुत है, क्योंकि ...",21.0,22.0,1
3,Mithali To Anchor Indian Team Against Australi...,आस्ट्रेलिया के खिलाफ वनडे टीम की कमान मिताली को,9.0,9.0,0
4,After the assent of the Honble President on 8t...,"8 सितम्‍बर, 2016 को माननीय राष्‍ट्रपति की स्‍व...",18.0,19.0,1

In [50]:
assert SOURCE_COL in df.columns, f"Column '{SOURCE_COL}' not found. Available: {list(df.columns)}"

df = df.dropna(subset=[SOURCE_COL]).copy()
print("Rows after dropping empty source rows:", len(df))

Rows after dropping empty source rows: 10000

In [52]:
df["word_count"] = df[SOURCE_COL].astype(str).apply(lambda x: len(x.split()))
filtered_df = df[(df["word_count"] >= MIN_LEN) & (df["word_count"] <= MAX_LEN)]

print(f"Sentences matching length filter ({MIN_LEN}-{MAX_LEN} words): {len(filtered_df)}")
filtered_df.head()

Sentences matching length filter (5-50 words): 9031

,English Sentences,Hindi Sentences,Word Count (English),Word Count (Hindi),Difference between Word Count (English) and Word Count (Hindi),word_count
0,"However, Paes, who was partnering Australia's ...",आस्ट्रेलिया के पाल हेनली के साथ जोड़ी बनाने वाल...,23.0,28.0,5,23
1,"Whosoever desires the reward of the world, wit...",और जो शख्स (अपने आमाल का) बदला दुनिया ही में च...,26.0,35.0,9,26
2,"""The value of insects in the biosphere is enor...","जैव-मंडल में कीड़ों का मूल्य बहुत है, क्योंकि ...",21.0,22.0,1,21
3,Mithali To Anchor Indian Team Against Australi...,आस्ट्रेलिया के खिलाफ वनडे टीम की कमान मिताली को,9.0,9.0,0,9
4,After the assent of the Honble President on 8t...,"8 सितम्‍बर, 2016 को माननीय राष्‍ट्रपति की स्‍व...",18.0,19.0,1,18

In [54]:
n = NUM_SENTENCES
if len(filtered_df) < n:
    print(f"Warning: only {len(filtered_df)} sentences available, using all of them.")
    n = len(filtered_df)

sampled_df = filtered_df.sample(n=n, random_state=RANDOM_SEED).reset_index(drop=True)
sampled_df = sampled_df.drop(columns=["word_count"])

print("Sampled sentences:", len(sampled_df))
sampled_df.head()

Sampled sentences: 100

,English Sentences,Hindi Sentences,Word Count (English),Word Count (Hindi),Difference between Word Count (English) and Word Count (Hindi)
0,We shall all be so grateful for any help that ...,"आप और आपकी सरकार जो भी संभव मदद दे सकेंगे, उसक...",19.0,18.0,1
1,"In its absence, the property will be classifie...",इसके न होने पर संपत्ति को वंशागत संपत्ति माना ...,11.0,11.0,0
2,Rupee Recovers From Record Low Of 74.46 Per US...,रुपया 24 पैसे मजबूत होकर 74.15 प्रत‍ि डॉलर पर ...,13.0,10.0,3
3,What is the size of the pharmaceutical packagi...,विश्व में फार्मा पैकेजिंग का कारोबार कितना बड़...,9.0,9.0,0
4,Remaining part of the salary will be paid when...,"’’ उन्होंने कहा, ‘‘शेष बचा वेतन तब दिया जाएगा ...",16.0,14.0,2

In [56]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
print("Tokenizer loaded.")

Tokenizer loaded.

In [57]:
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto",
)
model.eval()
print("Model loaded on:", model.device)

Model loaded on: cuda:0

In [58]:
test_sentence = sampled_df[SOURCE_COL].iloc[0]
print("Test source:", test_sentence)

prompt = f"""
You are a professional English to Hindi translator.

Rules:
- Translate English to Hindi
- Output ONLY the Hindi translation
- Use ONLY Devanagari script
- Do NOT use Roman Hindi
- Do NOT explain anything

English: {test_sentence}
Hindi:
"""

inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=MAX_NEW_TOKENS,
        do_sample=False,
        repetition_penalty=1.25,
        eos_token_id=tokenizer.eos_token_id,
        pad_token_id=tokenizer.eos_token_id,
    )

new_tokens = outputs[0][inputs["input_ids"].shape[1]:]
test_translation = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()
test_translation = test_translation.split("\n")[0].strip()

print("Test translation:", test_translation)

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Test source: We shall all be so grateful for any help that you and your Government may be able to render.
Test translation: हम सभी को आपके और सरकार का सहयोग करने में बहुत खुश होंगे।

In [ ]:
translations = []

for i, sentence in enumerate(tqdm(sampled_df[SOURCE_COL].astype(str).tolist(), desc="Translating")):

    prompt = f"""
You are a professional English to Hindi translator.

Rules:
- Translate English to Hindi
- Output ONLY the Hindi translation
- Use ONLY Devanagari script
- Do NOT use Roman Hindi
- Do NOT explain anything

English: {sentence}
Hindi:
"""

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=MAX_NEW_TOKENS,
            do_sample=False,
            repetition_penalty=1.25,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.eos_token_id,
        )

    new_tokens = outputs[0][inputs["input_ids"].shape[1]:]
    translation = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()
    translation = translation.split("\n")[0].strip()

    translations.append(translation)
    print(f"[{i}] EN: {sentence}\n     HI: {translation}\n")

print("Done translating", len(translations), "sentences.")

Translating:   0%|                                                                             | 0/100 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Translating:   1%|▋                                                                    | 1/100 [00:21<35:13, 21.34s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[0] EN: We shall all be so grateful for any help that you and your Government may be able to render.
     HI: हम सभी को आपके और सरकार का सहयोग करने में बहुत खुश होंगे।

Translating:   2%|█▍                                                                   | 2/100 [00:42<34:58, 21.41s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[1] EN: In its absence, the property will be classified as inherited property
     HI: अत्यंत विनाशकारी संपत्ति के अधीन नहीं होने, यह प्राप्तकर्मियों द्वारा निर्धारित किए गए समय अवधि में शास्यकृत् रूप से वर्गीकृत किया जाता है।

Translating:   3%|██                                                                   | 3/100 [00:58<30:22, 18.79s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[2] EN: Rupee Recovers From Record Low Of 74.46 Per US Dollar. Up 18 Paise
     HI: रुपये की स्थिति में रिकवरी हुई, और अमेरिका द्वारा प्रतिबंधित 74.46 पैसों पर आधुनिकतम वृद्धि दर 18 paisa बढ़ गई।

Translating:   4%|██▊                                                                  | 4/100 [01:10<25:48, 16.13s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[3] EN: What is the size of the pharmaceutical packaging industry?
     HI: क्या प्राकृतिक स्वास्थ्य के लिए आवश्यक दवाओं की खुराक में वृद्धि होगी, या नहीं?

Translating:   5%|███▍                                                                 | 5/100 [01:36<31:04, 19.63s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[4] EN: Remaining part of the salary will be paid when sufficient funds are available, the letter stated.
     HI: अंतिम भाग का वित्तीय राशि प्राप्त होने पर जब सीमित धन उपलब्ध हो तो, पत्र में उल्लेख किया गया।

Translating:   6%|████▏                                                                | 6/100 [02:02<34:07, 21.79s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[5] EN: Total cases: 49,650. Active cases: 26,118. Deaths: 642
     HI: तीन सौ नौ हजार और तीस लोगों में वायरस के प्रभावी ढंग से पता लगाया गया

Translating:   7%|████▊                                                                | 7/100 [02:16<30:00, 19.36s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[6] EN: She also worked in Tamil, Telugu, Hindi, Malayalam and Marathi movies.
     HI: सी के साथ-समय पर तमिल, तेलुगु और हिंदी, मलयालम और मराठी फिल्मों में भाग लिया।

Translating:   8%|█████▌                                                               | 8/100 [02:40<31:37, 20.63s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[7] EN: Kumbh Mela is a mass Hindu pilgrimage of faith in which Hindus gather to bathe in a sacred river.
     HI: कुम्भ मेला एक पौराणिक हिंदू धर्म के अनुष्ठानों से भरपूर भारतीय तीर्थयात्रा है, जिसमें लोग अपनी शुद्धता और आत्मनिर्वahan को दर्शाते हैं।

Translating:   9%|██████▏                                                              | 9/100 [03:05<33:40, 22.20s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[8] EN: But she cared for him with love and affection and sought to instill spiritual values in him.
     HI: लेकिन वह उसे प्यार और दया से उसकी ओर आकर्षित करती थीं  और उससे आध्यात्मिक मूलों को शामिल करने का प्रयास करती थीं।

Translating:  10%|██████▊                                                             | 10/100 [03:28<33:29, 22.32s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[9] EN: Holopainen has said in interviews that he did not wish to reveal her identity until new material was available because he did not want fans judging her by nothing more than a picture, or past work.
     HI: होलोपेन्सन ने साक्षात्कारों में कहा है कि वह अपनी पहचान तक नहीं बताया, जब तक कि नए प्रासंगिक उपलब्धता पर उसके लिए समय नहीं चला। उन्होंने दिखाई दिया कि वो एक फोटो, या उनक

Translating:  11%|███████▍                                                            | 11/100 [03:51<33:39, 22.69s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[10] EN: Both the countries discussed the existing bilateral cooperation initiatives in education and also agreed to further strengthen it by taking up several new initiatives.
     HI: भारत और पाकिस्तान के बीच स्थित दोनों सहयोगी गतिविधियों में शिक्षा पर विचार करने को चर्चा करे, इसके अलावा, उन्होंने कई नए योजनाओं को आगे बढ़ाने के लिए एक समग्र रूप

Translating:  12%|████████▏                                                           | 12/100 [04:10<31:18, 21.35s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[11] EN: "The Delhi Police searched the area but could not find anything.
     HI: दिल्ली पुलिस ने क्षेत्र में खोज नहीं हासिल करी।"

Translating:  13%|████████▊                                                           | 13/100 [04:28<29:36, 20.42s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[12] EN: "The garden complex is having many nearby tourist attractions as the Amer fort Palace, Jaigarh fort and Nahargarh fort along with much lush greenery.
     HI: "ग्रांड का पार्क कई नजदीकी पर्यटन आकर्षणों से भरपूर है, जिसमें अमर फोर्ट पैलेस, जयगरह फॉर्ट और नेहारंग राजमहल शामिल हैं, इसके अलावा बहुत लush greenery मिलता है।"

Translating:  14%|█████████▌                                                          | 14/100 [04:48<28:57, 20.20s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[13] EN: After that, the case has taken new turn.
     HI: अंततः केस में नया रूप ले गया।

Translating:  15%|██████████▏                                                         | 15/100 [05:11<29:55, 21.12s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[14] EN: Vermaji was not far from truth.
     HI: वर्मजी के पास त्रुटि नहीं थी।

Translating:  16%|██████████▉                                                         | 16/100 [05:32<29:42, 21.21s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[15] EN: "The results are expected to be announced in a couple of days.
     HI: "नतीजों को जल्द ही दिनों में घोषित करने वाला एक समूह होना चाहिए।

Translating:  17%|███████████▌                                                        | 17/100 [05:54<29:38, 21.43s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[16] EN: As per the orders of the Controller of Patents, Mumbai compulsory license has been granted to M/s Natco for manufacture of an anti-cancer drug NEXAVAR.
     HI: मुंबई में पेटेंट निरीक्षण के आदेशों के अनुसार, एमएस नाटको द्वारा एक एंटी-संक्रामक दवाई एनेकवाडर बनाने पर मजबूर लाइसेंस सुनिश्चित कराया गया।

Translating:  18%|████████████▏                                                       | 18/100 [06:12<27:35, 20.19s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[17] EN: It didnt happen in my time.
     HI: अत्यंत कठिन में ही यह घटना नहीं घटी।

Translating:  19%|████████████▉                                                       | 19/100 [06:31<26:58, 19.98s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[18] EN: Delhi should get more in view of elections.
     HI: दिल्ली को चुनावों में अधिक देखना होगा।

Translating:  20%|█████████████▌                                                      | 20/100 [06:52<27:08, 20.36s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[19] EN: However, 33 candidates have already been elected unopposed.
     HI: हालांकि, तीन३ उम्मीदवारों को वोट बिना हस्तक्षेप में चुना गया था।

Translating:  21%|██████████████▎                                                     | 21/100 [07:15<27:43, 21.05s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[20] EN: """We oppose the wrong stand taken by the Congress on CAA and NRC."
     HI: "हम विरोधी गलत दिशा को लेकर कांग्रेस पर सीएए और एनआरके पर अपनाने में सहमत नहीं हैं।"

Translating:  22%|██████████████▉                                                     | 22/100 [07:41<29:29, 22.69s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[21] EN: "The interest rates for customers availing a Home Loan above Rs 30 lakh have also been reduced by 10 basis points.
     HI: "क्लाइंट्स के लिए घर बिलों में अधिक राशि पर होने वाली दरें कम करने का प्रयास कर रहे हैं, जिसमें निवेश संबंधित शुल्क भी शामिल है।"

Translating:  23%|███████████████▋                                                    | 23/100 [08:08<30:42, 23.93s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[22] EN: He was taken to hospital, where he died.
     HI: वह को अस्पताल ले जाया गया, वहां उसकी मृत्यु हुई।

Translating:  24%|████████████████▎                                                   | 24/100 [08:21<26:11, 20.67s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[23] EN: Ministry of Railways permits Downloaded e-Aadhar Card as prescribed proof of identity for Rail Travel Purpose
     HI: रेलवे कार्यक्रमों में डाउनलोड्ड एएडHR परिस्थितियादायी संदेह पूर्वक राज्यालय देखभाल कर सकता है

Translating:  25%|█████████████████                                                   | 25/100 [08:45<27:05, 21.67s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[24] EN: A statement issued by the state government said a public holiday has been declared for the districts of Thiruvananthapuram, Kollam, Pathanamthitta, Alappuzha and Idukki in the state.
     HI: अंतिम निर्णय के बाद मुख्यमंडल सरकार द्वारा एक सामान्य अवकाश घोषित कर दिया गया है जिसकी शुरुआत 1 अप्रैल से, पंजाब और हर राज्यों सहित सभी अधिकृत विभागों को लेकर तीन मह

Translating:  26%|█████████████████▋                                                  | 26/100 [08:55<22:23, 18.15s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[25] EN: Now We have made the Koran easy for Remembrance. Is there any that will remember?
     HI: नवा हमें कोरान मी से रिकम्ब्रेशन कर दिया। है या नहीं?

Translating:  27%|██████████████████▎                                                 | 27/100 [09:14<22:29, 18.48s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[26] EN: "The movie is directed by Indra Kumar.
     HI: "मूवी का निर्देशक इंद्र कुमार है।"

Translating:  28%|███████████████████                                                 | 28/100 [09:38<24:03, 20.04s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[27] EN: Talking to reporters here on his return from a spiritual tour, he also said the state government should put additional pressure on the Central government to set up the Cauvery Management Board.
     HI: हाल के दौरान मैंने अपनी प्रारंभिक शिक्षा से लेकर उच्च शैक्षणीय स्तर तक सभी विषयों पर भाषण कर रहे हैं। वहां एक आध्यात्मिक यात्रा के बाद उन्होंने कहा, "राज्य सरकारें अध

Translating:  29%|███████████████████▋                                                | 29/100 [10:04<25:36, 21.65s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[28] EN: 'Gold Coins In Tamil Nadu Temple' - 1 News Result(s)
     HI: "तामिळनदु मंदिर के पास गोल्ड कॉइन्स"

Translating:  30%|████████████████████▍                                               | 30/100 [10:25<25:02, 21.47s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[29] EN: You should all write to Khattar uncle (Haryana Chief Minister Manohar Lal Khattar) and Captain uncle (Punjab Chief Minister Amarinder Singh) asking them to take care of your health, said Kejriwal.
     HI: कृपया सभी को खट्टर पिता (हारियान राज्य मुख्यमंत्री) महामोहन लाल खट्तर से पत्रकारों को अपनी स्वास्थ्य देखभाल करने के लिए अनुरोध करें, कहांसे निकल जाएं।  यह

Translating:  31%|█████████████████████                                               | 31/100 [10:45<24:10, 21.02s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[30] EN: NClT bench members BSV Prakash Kumar and V Nallasenapathy said that Mistry was ousted as chairman because the Tata Sons Board and its majority shareholders had lost confidence in him.
     HI: एनसीए ने बेंच मेम्बर्स BSV प्रकाश कुमार और VNालासेनापथी ने कहा है कि मिस्टरी टाटा संस्कृतियों बोर्ड और उसके अधिकांश शेयरधारकों ने उन्हें चुनने पर विश्वास खो

Translating:  32%|█████████████████████▊                                              | 32/100 [11:07<24:18, 21.45s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[31] EN: "The IT Secretary, who also happens to be the Secretary to the Chief Minister, was a frequent visitor to Swapnas residence.
     HI: "इट सेक्रेटरी, जो कि चीफ मंत्री अध्यक्षा द्वारा, एक नियमित यात्रियों में भी है और वह अपने घर पर कई बार रहता था।"

Translating:  33%|██████████████████████▍                                             | 33/100 [11:29<24:09, 21.63s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[32] EN: He shared this on his Instagram account.
     HI: वह ने अपनी इंस्टाग्राम अकाउंट पर यह साझा किया।

Translating:  34%|███████████████████████                                             | 34/100 [11:35<18:36, 16.92s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[33] EN: Ghosh chooses not to talk about them
     HI: गोश को उन लोगों से बात नहीं करनी चाहिए।

Translating:  35%|███████████████████████▊                                            | 35/100 [11:59<20:33, 18.97s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[34] EN: "She is based in both London and Tokyo, and is very popular in Japan, with her style being described as ""British punk and recycled materials molded into voluminous and voluptuous Victorian-inspired dresses""."
     HI: "वह दोनों लंदन और टोक्यो में रहती है  वह भारत के जापान में बहुत प्रसिद्ध है, उसका स्टाइल ब्रिटिश पैंक और रिक्लेमेड्ड्स बनाए गए वोलुपटूस वाइकलिंग डेस्हबेबिस क

Translating:  36%|████████████████████████▍                                           | 36/100 [12:24<22:06, 20.73s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[35] EN: "They also stressed on the requirement for Pakistan to produce evidence of proper trial which it claimed to have conducted in the case.
     HI: "वे पाकिस्तान को अपनी अदालत में उचित तरीका से न्यायिक सत्र चलाते हैं जिन्होंने उन पर आरोप लगाए थे।"

Translating:  37%|█████████████████████████▏                                          | 37/100 [12:46<22:24, 21.34s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[36] EN: Later, Shri Sharma will meet Mr. Armando Inroga, Minister of Industry and Trade, Mozambique, where the two Ministers will discuss trade and investment related issues.
     HI: अगले कार्यक्रम में श्री शर्मा ने अरमंडो इंरोगा, उद्योग और वाणिज्य मंत्री, मोजाम्बिक, जिस पर दोनों अधिवक्ताओं के बीच संबंध बनाने के लिए चर्चा करेगा।

Translating:  38%|█████████████████████████▊                                          | 38/100 [13:03<20:38, 19.98s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[37] EN: We are steadily climbing up on the innovations rankings in the world.
     HI: हम स्वाभाविक रूप में नवाचारों की तेजी वाले दुनिया भर में अपने उत्कृष्टताओं पर प्रमुख ध्यान केंद्रित कर रहे हैं।

Translating:  39%|██████████████████████████▌                                         | 39/100 [13:30<22:26, 22.08s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[38] EN: "The Romans had a passion for gladiatorial spectacles.
     HI: "रोमनों ने ग्लादियोरियल स्पेक्सेस का प्रेम दिखाया।"

Translating:  40%|███████████████████████████▏                                        | 40/100 [13:51<21:44, 21.74s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[39] EN: "The police have arrested both the accused and they were presented before Court.
     HI: "पुलिस ने दोनों आरोपियों को गिरफ्तार कर लिया है और उन्हें अदालत में पेश करने पर तैयारी चल रही है।"

Translating:  41%|███████████████████████████▉                                        | 41/100 [14:13<21:20, 21.71s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[40] EN: "The gist of the article 'These Remedies are not Enough', published on 9th June, was given to the court and jury. 9
     HI: "इस प्रकार के अन्य उपायों में से एक है जो निम्नलिखित विवरण देता है, यहां तक ​​कि उन्हें अपनी सहमति नहीं देना। इस बात पर चर्चा करने, और उनके लिए आवश्यक सबूत इकट्ठा करना, याद

Translating:  42%|████████████████████████████▌                                       | 42/100 [14:42<23:06, 23.91s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[41] EN: Here a look at who said what:
     HI: अत्यंत विश्वासी हैं लोगों के बीच में से, जो अपना समय पूर्ण कर रहे हैं। उनके दिल में, एक खुशहाल और शांतिपूर्ण परिवार रहता है। वह हमेशा नई चीजें करने के इच्छुक थे। उन्ह

Translating:  43%|█████████████████████████████▏                                      | 43/100 [15:00<21:09, 22.27s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[42] EN: Khan secured 176 votes while his only rival Sharif got 96 votes.
     HI: खन ने अपनी एकमात्र प्रतिद्वंद्वी शारीफ को 96 वोट्स से जीत लिया था।

Translating:  44%|█████████████████████████████▉                                      | 44/100 [15:19<19:43, 21.14s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[43] EN: "The Congress, on the other hand, has fielded Ajay Rai from Varanasi.
     HI: "कांग्रेस के बावजूद, अजय राई से वाराणसी में चुना गया है।"

Translating:  45%|██████████████████████████████▌                                     | 45/100 [15:41<19:45, 21.55s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[44] EN: As long as they have to depend on black money and dubious deals to collect their funds we will continue to see the sort of ugly wheeling and dealing we saw on the Tehelka tapes.
     HI: तलेका टेप्स में दिखाई दे रही है कि वे अपने पैसों से निराश नहीं हैं और उनको धोखाधड़ी करके उन्हें धन इकट्ठा करने के लिए मजबूर करते। हमारे सरकार को यह पता चलना चाहिए

Translating:  46%|███████████████████████████████▎                                    | 46/100 [16:04<19:38, 21.82s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[45] EN: He is unwavering when it comes to safeguarding national interests and furthering national progress.
     HI: वह स्वतंत्र राष्ट्रमित कार्यों और देश में आगे बढ़ने पर विश्वास रखता है।

Translating:  47%|███████████████████████████████▉                                    | 47/100 [16:28<19:56, 22.57s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[46] EN: PM Modi calls upon international community to unite against terrorism for the sake of humanity
     HI: भारत के प्रधान मंत्री नरेंद्र टोडरा ने अंतर्राष्ट्रीय समुदाय से विरोध करने और दुनिया भर को एकजुट करके आतंकवाद के खिलाफ लड़ने के लिए अपनी बात कही।

Translating:  48%|████████████████████████████████▋                                   | 48/100 [16:55<20:46, 23.97s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[47] EN: It owes its existence to the Delhi Special Police Establishment Act, 1946.
     HI: दिल्ली स्पेशल पुलिस एस्टेट act, 1946 के अनुसार यह अपना विकास करता है।

Translating:  49%|█████████████████████████████████▎                                  | 49/100 [17:11<18:21, 21.61s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[48] EN: Property registration: Details of registered deeds
     HI: मालिकता की रजिस्ट्रेशन - मालिकों द्वारा स्थापित निवासी दस्तावेज़

Translating:  50%|██████████████████████████████████                                  | 50/100 [17:45<20:54, 25.09s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[49] EN: "The film is scheduled to release on February 21, 2020.
     HI: "फिल्म का रिलीज़ दिन २१, २०२० में होने वाली थी।"

Translating:  51%|██████████████████████████████████▋                                 | 51/100 [18:10<20:32, 25.16s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[50] EN: Rajasthan Government has decided to keep close all schools, colleges, coaching centers, gyms, cinemas and theaters etc.
     HI: राजस्थान सरकार ने सभी स्कूलों, कॉलेजों और ट्रेनिंग केंद्रों, गेम्स, फिल्में, थिएटर आदि सहित सभी शिक्षा सुविधाओं पर पूर्ण रूप से बंद करने का निर्धारण किया।

Translating:  52%|███████████████████████████████████▎                                | 52/100 [18:35<20:09, 25.20s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[51] EN: What PDP has to say
     HI: पीडीपी को सुनने वाला है

Translating:  53%|████████████████████████████████████                                | 53/100 [19:03<20:27, 26.11s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[52] EN: Wreaths were laid by the Lieutenant General BK Chopra, Director General AFMS and Senior Colonel Commandant and the three Director Generals Medical Service of Army, Navy and Air Force to pay homage to the martyrs.
     HI: अर्जनों के लिए विशेष प्रार्थना में शामिल होने, सैन्य बलों और राजनीतिक दलों द्वारा, 1947 तक पहुंचाई गई थी। यहां पर उन्होंने अपनी युद्धपूर्ण भूमि को समर्पित करने के

Translating:  54%|████████████████████████████████████▋                               | 54/100 [19:31<20:18, 26.48s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[53] EN: It is generally presumed that two successive names are teacher and pupil.
     HI: तीनों के लिए शिक्षक और छात्र होना सामान्य मानती जाएगी।

Translating:  55%|█████████████████████████████████████▍                              | 55/100 [19:58<19:56, 26.58s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[54] EN: After presenting the Kalash , union Minister held a press conference and briefed media about the vision behind this step
     HI: कलाश के बाद, संयुक्त मंत्री ने अपना प्रस्तुति देते हुए समाचार पत्रकारों तक विस्फोटक जानकारी साझा करने और उनको इस पहल पर चर्चा करने के लिए एक अधिकांशतः शुरू कर द

Translating:  56%|██████████████████████████████████████                              | 56/100 [20:22<19:00, 25.92s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[55] EN: It is a place of magnificent natural beauty and a Hindu pilgrim spot too
     HI: यह एक महान प्राकृतिक सुंदरता और हिंदू तीर्थयात्री के लिए भूमि में स्थित है

Translating:  57%|██████████████████████████████████████▊                             | 57/100 [20:46<18:10, 25.36s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[56] EN: """Tejashwi is leader of RJD but he is not the leader of the Grand Alliance"", he said."
     HI: "तेजश्वी राजद के नेता है लेकिन ग्रांड अलियन्स में उनका संभावित अध्यक्ष नहीं है।"

Translating:  58%|███████████████████████████████████████▍                            | 58/100 [21:12<17:49, 25.47s/it]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[57] EN: Olive oil is beneficial for your health in multiple ways.
     HI: अलोह्यू में स्वास्थ्य के लिए कई तरीकों पर फायदा होता है।

In [ ]:
sampled_df["translation"] = translations
sampled_df.head()

In [ ]:
has_reference = REFERENCE_COL in sampled_df.columns

if not has_reference:
    print(f"Reference column '{REFERENCE_COL}' not found. Available columns: {list(sampled_df.columns)}")
    print("Set REFERENCE_COL in the config cell to your actual reference-translation column, then re-run from here.")
else:
    print("Reference column found:", REFERENCE_COL)

In [ ]:
hypotheses = sampled_df["translation"].astype(str).tolist()
references = sampled_df[REFERENCE_COL].astype(str).tolist()

corpus_bleu = sacrebleu.corpus_bleu(hypotheses, [references]).score
corpus_chrf = sacrebleu.corpus_chrf(hypotheses, [references]).score
corpus_ter = sacrebleu.corpus_ter(hypotheses, [references]).score

print("Corpus BLEU:", corpus_bleu)
print("Corpus chrF:", corpus_chrf)
print("Corpus TER:", corpus_ter)

In [ ]:
bleu_scores = []
chrf_scores = []
ter_scores = []

for hyp, ref in zip(hypotheses, references):
    s_bleu = sacrebleu.sentence_bleu(hyp, [ref]).score
    s_chrf = sacrebleu.sentence_chrf(hyp, [ref]).score
    s_ter = sacrebleu.sentence_ter(hyp, [ref]).score

    bleu_scores.append(s_bleu)
    chrf_scores.append(s_chrf)
    ter_scores.append(s_ter)

sampled_df["bleu"] = bleu_scores
sampled_df["chrf"] = chrf_scores
sampled_df["ter"] = ter_scores

sampled_df.head()

In [ ]:
sampled_df.to_csv(OUTPUT_CSV, index=False)
print("Saved to", OUTPUT_CSV)